version: '3.8'

services:
  neo4j_db:
    image: neo4j:5.8.0
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  neo4j_data:
